### ISSUE TITLE
关于运行结果评估的问题

### ISSUE THREAD

**Issue by biluox** [junieberry/MARS#1]
我按照预设在Scientific这个数据集上运行了两次仓库代码，两次的结果都显示，R@10 在0.12左右，N@10在0.073左右，这个和论文的结果相差略大，我做出的唯一改动是，取消了一开始的零模型预测，直接开始走训练评估。请问是否是默认设置上存在问题，还是有什么我不清楚的设置方面。

**Comment by junieberry** [comment]
Hi @biluox,

Thank you for bringing this potential issue to our attention. There was an error in the dataset preprocessing part, and I have modified the code and committed the fix. Please try running it again. I appreciate your feedback.
